### ISSUE TITLE
Deep sleep and Wake on Lan are not working.

### ISSUE THREAD

**Issue by gorans** [Hackintoshlifeit/GA-Z490M-Gaming-X#1]
Hi,
I used Your EFI for my build. Only differences are no BT card and graphic card iz RX 570.
My hack powe light stays on when I enter sleep and I can't wake it with WOL (enabled in BIOS and in Energy Saver.
Do You have any advice?

Best regards,
Goran

**Comment by ghost** [comment]
does it go into sleep? and wake?  commission of to imply a patch in ssdt for usb.

**Comment by gorans** [comment]
I manage to fix all my problems. Updated to 0.6.2, correct SSDT and IntelMausiEthernet instead of IntelMausi, everything is working now including sleep and WOL.
Thanks.
