### ISSUE TITLE
[Question] SysReport and DevirtMmio

### ISSUE THREAD

**Issue by dreamwhite** [Hackintoshlifeit/GA-Z490M-Gaming-X#2]
Hi there ^^
I found your repo while digging on the web and decided to give it a look. May I gently ask you to attach your OpenCore SysReport result? For more infos check [here](https://github.com/utopia-team/opencore-debug).

Also what about Mmio Devirt? Have you found your MMIOWhitelist values? If so can you gently attach the OpenCore Debug log with Target 67 and DevirtualiseMmio enabled?

Best regards
dreamwhite

**Comment by Baio1977** [comment]
Hi Dream, Ioreg attached and now I try to satisfy your other requests, sorry my English I use the translator
